services:
  api:
    image: ${DOCKER_REGISTRY-}lancamentoapi
    build: .
    ports: 
       - "8081:80"
    depends_on:
       - sqldata
       - rabbitmq
  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Senha@2023
      - ACCEPT_EULA=Y
    volumes:
      - c:\dados\volumes\mssql:/var/opt/msql/data
    ports:
      - "1450:1433"  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672  
      - 15672:15672 
    volumes: 
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456